// Daily stats fetch
export const SONA_DAILY_FETCH_REQUEST = 'SONA_DAILY_FETCH_REQUEST';
export const SONA_DAILY_FETCH_SUCCESS = 'SONA_DAILY_FETCH_SUCCESS';
export const SONA_DAILY_FETCH_FAILURE = 'SONA_DAILY_FETCH_FAILURE';

// Range stats fetch (rolling / historical)
export const SONA_RANGE_FETCH_REQUEST = 'SONA_RANGE_FETCH_REQUEST';
export const SONA_RANGE_FETCH_SUCCESS = 'SONA_RANGE_FETCH_SUCCESS';
export const SONA_RANGE_FETCH_FAILURE = 'SONA_RANGE_FETCH_FAILURE';

// Weekly stats fetch
export const SONA_WEEKLY_FETCH_REQUEST = 'SONA_WEEKLY_FETCH_REQUEST';
export const SONA_WEEKLY_FETCH_SUCCESS = 'SONA_WEEKLY_FETCH_SUCCESS';
export const SONA_WEEKLY_FETCH_FAILURE = 'SONA_WEEKLY_FETCH_FAILURE';

// Weekly trend fetch (last N weeks for week-over-week chart)
export const SONA_WEEKLY_TREND_REQUEST = 'SONA_WEEKLY_TREND_REQUEST';
export const SONA_WEEKLY_TREND_SUCCESS = 'SONA_WEEKLY_TREND_SUCCESS';
export const SONA_WEEKLY_TREND_FAILURE = 'SONA_WEEKLY_TREND_FAILURE';
